deployment:
  # deployment.image -- tidewhisperer Docker image
  image: tidepool/tide-whisperer:master-latest
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  # hpa.enabled -- whether to create a horizontal pod autoscalers for all pods of given deployment
  enabled: false
  # hpa.minReplicas -- minimum number of replicas that HPA will maintain
  minReplicas: 1
  # hpa.maxReplicas -- maximum number of replicas that HPA will maintain
  maxReplicas: null
pdb:
  enabled: false
  minAvailable: "50%"
mongo:
  secretName: mongo
serviceMonitor:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
