secret:
  enabled: false
  data_:
    ServiceAuth: ""
deployment:
  image: tidepool/platform-prescription:master-latest
  replicas: 1
  podAnnotations: {}
  env:
    store:
      s3:
        bucket: "asset"
resources: {}
securityContext: {}
hpa:
  # hpa.enabled -- whether to create a horizontal pod autoscalers for all pods of given deployment
  enabled: false
  # hpa.minReplicas -- minimum number of replicas that HPA will maintain
  minReplicas: 1
  # hpa.maxReplicas -- maximum number of replicas that HPA will maintain
  maxReplicas: null
pdb:
  enabled: false
  minAvailable: "50%"
mongo:
  secretName: mongo
nodeSelector: {}
tolerations: []
affinity: {}
